package life.study.community.model;

public class NotificationKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.id
     *
     * @mbggenerated Sat Feb 25 21:21:36 CST 2023
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.id
     *
     * @return the value of notification.id
     *
     * @mbggenerated Sat Feb 25 21:21:36 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.id
     *
     * @param id the value for notification.id
     *
     * @mbggenerated Sat Feb 25 21:21:36 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }
}