package life.study.community.model;

public class QuestionKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.id
     *
     * @mbggenerated Mon Feb 13 22:10:43 CST 2023
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.id
     *
     * @return the value of question.id
     *
     * @mbggenerated Mon Feb 13 22:10:43 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.id
     *
     * @param id the value for question.id
     *
     * @mbggenerated Mon Feb 13 22:10:43 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }
}